/**
 * Replace or extend this array with your patch data (or load from JSON/API).
 * category: "unit" | "ability" | "ai" | "drop"
 * change: "buff" | "nerf" | "rework" | "neutral"
 */
window.PATCH_ENTRIES = [
  {
    id: "1",
    name: "Grunt",
    category: "unit",
    change: "buff",
    patch: "2.0.1",
    summary: "Base armor increased by 1. Attack speed improved slightly in late tiers.",
    detail: "Armor 1 → 2. Intended to stabilize early melee trades vs. ranged creeps.",
  },
  {
    id: "2",
    name: "Frost Nova",
    category: "ability",
    change: "nerf",
    patch: "2.0.1",
    summary: "Slow duration reduced at all ranks. Mana cost increased.",
    detail: "Duration −15% at max rank. Mana +10 flat.",
  },
  {
    id: "3",
    name: "Creep camp AI",
    category: "ai",
    change: "rework",
    patch: "2.0.0",
    summary: "Neutral camps leash farther and reset health if fully disengaged.",
    detail: "Leash radius +20%. Full reset after 8s out of combat.",
  },
  {
    id: "4",
    name: "Dragon chest",
    category: "drop",
    change: "nerf",
    patch: "1.9.4",
    summary: "Rare orb drop rate reduced. Added bad-luck protection after 12 clears.",
    detail: "Orb 12% → 9%. Guarantee token every 15 clears (max stack 3).",
  },
  {
    id: "5",
    name: "Priest",
    category: "unit",
    change: "nerf",
    patch: "2.0.1",
    summary: "Heal over time effectiveness reduced vs. heroes.",
    detail: "HoT −20% on hero targets; unchanged on units.",
  },
  {
    id: "6",
    name: "Blink",
    category: "ability",
    change: "rework",
    patch: "2.0.0",
    summary: "Cast time added; range scales with level.",
    detail: "0.15s wind-up. Range 400/500/600/700 by rank.",
  },
  {
    id: "7",
    name: "Insane AI economy",
    category: "ai",
    change: "buff",
    patch: "1.9.4",
    summary: "Insane AI receives slightly less passive gold trickle but better unit upkeep efficiency.",
    detail: "Gold trickle −5%. Upkeep breakpoint thresholds +1 supply each.",
  },
  {
    id: "8",
    name: "Ancient treant drop",
    category: "drop",
    change: "buff",
    patch: "2.0.1",
    summary: "Chance for consumable drops increased; added small dust chance.",
    detail: "Consumable 8% → 11%. Dust of Appearance 2% on elite only.",
  },
  {
    id: "9",
    name: "Wind Walk",
    category: "ability",
    change: "nerf",
    patch: "1.9.4",
    summary: "Bonus move speed reduced. Fade time when attacking increased.",
    detail: "MS bonus 40/60/80 → 35/50/65. Attack fade +0.2s.",
  },
  {
    id: "10",
    name: "Tauren Chieftain",
    category: "unit",
    change: "rework",
    patch: "2.0.0",
    summary: "Endurance Aura reworked to grant flat HP regen instead of %.",
    detail: "Now +0.5/1/1.5 HP/s aura; no longer scales off max HP.",
  },
  {
    id: "11",
    name: "Boss loot table",
    category: "drop",
    change: "neutral",
    patch: "2.0.0",
    summary: "Side-bosses now drop tokens instead of random epics.",
    detail: "Tokens exchangeable at hub vendor; reduces duplicate frustration.",
  },
  {
    id: "12",
    name: "Harassment AI",
    category: "ai",
    change: "buff",
    patch: "2.0.1",
    summary: "AI more likely to scout expos and interrupt expansions on Hard+.",
    detail: "Scout frequency +30%. Worker attack priority when undefended.",
  },
];
